---
kind: pipeline
type: docker
name: default

steps:
  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/cloudflared
      tags:
        - ${DRONE_TAG}
        - latest
      when:
        event:
          - tag
---
kind: signature
hmac: baa59daff6995971bbb4f8ccc95e72ec1eb8b05d140437a110c67b6d5d4be211

...
