---
kind: pipeline
type: docker
name: default

steps:
  - name: source
    image: alpine:3.11
    commands:
      - apk add --update --no-cache curl git
      - git clone -n https://github.com/cloudflare/cloudflared.git
      - cd cloudflared
      - LATEST=$(git describe --abbrev=0)
      - if curl -sfL https://hub.docker.com/v2/repositories/ezkrg/cloudflared/tags/$LATEST > /dev/null; then echo "tag $LATEST already exist"; exit 78; fi
      - git checkout $LATEST
      - cd ..
      - echo -n "$LATEST,latest" > .tags

  - name: release
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/cloudflared
      when:
        event:
          - cron
        cron:
          - nightly
---
kind: signature
hmac: e00fd36ebfaae10cb9a5a775a9ba351421b5c2088fb22caeef50f4d3e5dc5b48

...
