---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: plugins/docker
    settings:
      username:
        from_secret: DHU
      password:
        from_secret: DHP
      repo: ezkrg/cloudflared
      tags: latest
---
kind: signature
hmac: f478edd8abef3175f5720622b9fe80273549e009e1d68c487e37daa16c4c6394

...
